server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: file:env
